### ISSUE TITLE
set unescaped property default value

### ISSUE THREAD

**Issue by tristanpemble** [gossi/php-code-generator#10]
I'd like to be able to generate a property that is an array that uses constants for keys, like

~~~
    public static $fooBar = [
        Foo::FOO => 'foo',
        Foo::BAR => 'bar',
    ];
~~~

it would be nice to be able to pass in something that is not automatically escaped via `var_export`

**Comment by gossi** [comment]
sounds like a great addition. Send a PR for what you need.
