### ISSUE TITLE
Consider tagging a release

### ISSUE THREAD

**Issue by moufmouf** [gossi/php-code-generator#14]
Hi @gossi !

Two packages are dependent on php-code-generator ([list here](https://packagist.org/packages/gossi/php-code-generator/dependents)).
There is no release tagged and that means that users using those packages must add 

```
"minimum-stability": "dev",
"prefer-stable": true,
```

to their `composer.json` file.

This can be an issue for several users (see here: https://github.com/Wabel/zoho-crm-orm/issues/7)

Would you consider tagging a release (maybe a 0.1.0 or even 0.0.1 if you don't consider your package fully stable yet?) That would help users of your package a lot!

Best regards,
David.

// cc @WizMik

**Comment by gossi** [comment]
Yes, you are absolutely right. I'm at the moment using my code-generator in one of my own packages and also working on the depending packages as well (already found some bugs there). I want to have it done by the end of november so I can fix all the issues that appear within that time and then tag a release.

**Comment by gossi** [comment]
My tests turned well and I tagged a release. Have fun :)

**Comment by moufmouf** [comment]
:+1:
