### ISSUE TITLE
Library requires abandoned packages

### ISSUE THREAD

**Issue by XedinUnknown** [gossi/php-code-generator#17]
Hi,

First of all, I'd like to thank the author of this library. Not only does this seem to support traits and interfaces, which is exactly what I'm looking for, but from what I can see, many if not all `private` properties have been refactored to `protected`. This is much better, and is really in line with my own philosophy: why deny the user of your code the ability to change things in their extension of your code? In the light of these and many other things, this library is superior to the once great [`schmittjoh/cg-library`](https://github.com/schmittjoh/cg-library).

Now, to the problem. When running `composer install` with this package required, I get the following message:

```
Package gossi/common is abandoned, you should avoid using it. Use phootwork/lang instead.
Package gossi/collection is abandoned, you should avoid using it. Use phootwork/collection instead.
```

This is the first time I got something like this, so 2 questions:

1. Are these packages really abandoned, and the `phootwork` packages are superior?
2. If abandoned, will this problem be resolved? If it won't, I assume I cannot just switch to using the `phootwork` packages; am I right?

**Comment by gossi** [comment]
Hey,
`phootwork/lang` ist the successor of `gossi/common` and `phootwork/collection` is the successor of `gossi/collection`, so this is correct. I am wondering, why composer wants to install them as I thought I pointed all dependencies to the phootwork framework. I will recheck this, thanks for mentioning.

**Comment by gossi** [comment]
Can you try again with the new version?
