### ISSUE TITLE
PhpParameter::fromReflection() doesn't take default parameter values

### ISSUE THREAD

**Issue by mijohansen** [gossi/php-code-generator#32]
Ill try to explain. When creating a method from reflection default parameter gets messed up.

When I have a class with a default

``` php
class SomeClass {

    public function someMethod($someOptionalParameter = null) {
    return true;
    }

}

use gossi\codegen\model\PhpClass;
use gossi\codegen\generator\CodeFileGenerator;

$phpClass = PhpClass::fromReflection(new ReflectionClass("SomeClass"));
$gen = new CodeFileGenerator();

echo $gen->generate($phpClass);
```

Will produce:

``` php
class SomeClass {

    /**
     * @param mixed $someOptionalParameter
     */
    public function someMethod($someOptionalParameter = ) {
        return true;
    }
}
```

Where as you can notice the default value is missing.

Hope this helps. 

Guess the problematic area is PhpParameter::fromReflection()  line 64

**Comment by motia** [comment]
Confirmed. But the problem is only for parameters defaulted to null.
Look at my fix.
 #33

**Comment by gossi** [comment]
Confirmed. There are some more problems with default parameter values (and also property values in classes). I must address this, however not before mid october, because I need to get my thesis done.

Ref #31
