### ISSUE TITLE
PhpInterface::fromReflection requires custom code

### ISSUE THREAD

**Issue by mozzymoz** [gossi/php-code-generator#34]
I wanted to use `PhpInterface::fromReflection` on the SPL Interface `Iterator`, however I get an error.

Code:

``` php
$pInterface = PhpInterface::fromReflection(new \ReflectionClass(\Iterator::class));
```

Error:

```
file(): Filename cannot be empty

vendor/gossi/php-code-generator/src/utils/ReflectionUtils.php:78
vendor/gossi/php-code-generator/src/model/PhpInterface.php:31
```

I see that actually the Reflection Class is only used to retrieve the file in order to parse the file content.
Might want to update the documentation to warn devs about this behaviour :)

**Comment by gossi** [comment]
Can you provide a test object, which I can also add to the test suite? Can be a minimal working example of yours, which is causing the problem at the moment.

**Comment by gossi** [comment]
Unfortunately the Reflection classes by php don't offer all the information needed to completely parse a certain code fully into php code generators model. As such the file is read (e.g. reading the body for all methods or constants (in the next release)). I am more wondering why you read in a built-in code class? What's the matter? I'm wondering how to handle possible error messages in that case. Thanks for helping out on this one.

**Comment by gossi** [comment]
I'm asking because I'm working on the code-generator at the moment. I have more and more the tendency to remove the `fromReflection` methods in order to read in code via the `fromFile` method. Well, `fromReflection` still could serve as shortcut to this but actually it would mean maintain two "parsers" while actually reflection requires too much utility code to read in all the information making it very much unreliable.

**Comment by mozzymoz** [comment]
Hey there,
the reason was for me to automatically copy abstract methods from the interface to a generated class but I found a different way. I think if you threw an Exception when the `ReflectionClass::getFileName === false`
Or completely remove it as you mentioned since, one can use the the fromFile Method with a ReflectionClass Object.

Cheerio

**Comment by gossi** [comment]
Yes I see, that was the case I was thinking about after writing this comment. However, getting class signatures is not the purpose of this library and should be done apart from that (at least the parsing parts, the models are great to use them). The `formReflection()` methods will be deprecated in the next version and are just a shortcut to `static::fromFile($reflection->getFileName())`.

**Comment by mozzymoz** [comment]
:+1:
