### ISSUE TITLE
PhpProperty doesn't support expressions

### ISSUE THREAD

**Issue by marcj** [gossi/php-code-generator#39]
In `https://github.com/gossi/php-code-generator/blob/master/src/generator/builder/PropertyBuilder.php#L18` it only checks for a set value.

```php
PhpProperty::create('myProp')
    ->setExpression('[0, 1]');
```

does not work in terms of it just doesn't write a default property value. I changed the code at line 18 to `if ($model->hasValue() || $model->isExpression()) {` and that fixed it.

**Comment by cristianoc72** [comment]
Imho there's no problem here.
`hasValue` function do exactly what you expected: https://github.com/gossi/php-code-generator/blob/master/src/model/parts/ValuePart.php#L118.

At https://github.com/gossi/php-code-generator/blob/master/tests/generator/PropertyGeneratorTest.php#L77 the relative test is green.
To be 100% sure, I added the following:
```php
$prop = PhpProperty::create('myProp'')->setExpression('[0, 1]');
$this->assertEquals('public $myProp = [0, 1];'."\n", $generator->generate($prop));
``` 
and again all tests are green.

**Comment by marcj** [comment]
Oh weird, I had to remove all `setExpression` calls to get default values. Will look into it again

**Comment by cristianoc72** [comment]
Well, there's a problem when you pass a variable containing an array, because `setExpression` expects a string.

The following test case fails:
```php
$array = [0, 1];
$prop = PhpProperty::create('foo')->setExpression($array);
```
while the following it's ok:
```php
$array = [0, 1];
$prop = PhpProperty::create('foo')->setExpression(var_export($array, true));
$this->assertEquals('public $foo = array(0, 1);'."\n", $generator->generate($prop));
```
The good old `setDefaultValue` accepted also arrays: maybe the problem is around here.

**Comment by gossi** [comment]
Yep. `setExpression()` takes a string. That is, because when you do sth like:

```php
$model->setExpression(['my' => 'fancy, 'array' => 'with stuff']);
```

won't be output as it is put in. Now you pass in values as you want them to be generated.
