### ISSUE TITLE
Writer is not configurable enough

### ISSUE THREAD

**Issue by mb-joker** [gossi/php-code-generator#44]
All Builders depend on the writer which just has 2 options (indentation) to configure the coding style with which the class/method/function etc. is build. Best example from ClassBuilder `$this->writer->writeln(" {\n")->indent();` the written line should definitely be configurable in the writer e.g. if you want to have the bracket in a new line: "\n{".

Apart from this, very nice generator, like it!

**Comment by gossi** [comment]
You mean the `\n` to be configurable?

**Comment by mb-joker** [comment]
my question was basicly the same as https://github.com/gossi/php-code-generator/issues/49
and with your answer given: YES WE NEED PROFILES! :D
Everyone could create an own profile to match his/her coding style.

**Comment by gossi** [comment]
See #54
