### ISSUE TITLE
Empty Comments are automaticly added (PHPDoc)

### ISSUE THREAD

**Issue by mb-joker** [gossi/php-code-generator#45]
No matter if I load a Class from a file or create a complete new one like in the example from the documentation, if a method/class does not have a comment, it will always get an empty one `/**
	 */`

**Comment by gossi** [comment]
That's true, because empty docblock generation enabled by default, see here: https://php-code-generator.readthedocs.io/en/latest/generator.html

You can easily deactivate this.

**Comment by mb-joker** [comment]
thanks, sovled!
