### ISSUE TITLE
SetBody - How to write multiple line in a class/function. 

### ISSUE THREAD

**Issue by icaxis** [gossi/php-code-generator#50]
I don't know if it's issue or not. But I don't how to add multiple line my class function.

I have tried : 
` ->setBody('$this->driver = $driver')
 ->setBody('$this->driver2 = $driver2');`

But it didn't work, it only takes the last one. Sure more would be great, but so far it a pretty system.

**Comment by gossi** [comment]
Of course it takes the input of the second call as it is a `set` method and neither `add` or `append`. To use new lines simply use standard php:

`->setBody("// line one \n//line two");`

at best you use template systems for method bodies as [mentioned in the docs](https://php-code-generator.readthedocs.io/en/latest/best-practices.html#template-system-for-code-bodies).

**Comment by icaxis** [comment]
Yeah! But a `add` or `append` would be great if it was implemented. Because it will be difficult for indentation, to manage semicolon and lot of a hassle for a `foreach`.

I've checked the doc and couldn't quite get it how to `add` or `append`, probably because of my low English understanding. Could, please paste a similar code.

Here what I want to accomplish in class -> function:
`public function name(){
        $supervar = 'xyz';
         if($supervar != ''){
               die('nice indenttion');
         }
}`

**Comment by gossi** [comment]
There you go:

```
<?php
$code = "$supervar = 'xyz';\nif($supervar != '') {\n\tdie('nice indenttion');\n}";
$method->setBody($code);
```

but as mentioned use a template system for method bodies.

**Comment by icaxis** [comment]
Thanks. I will work on that.
