### ISSUE TITLE
Updated dependencies, specifically nikic/php-parser

### ISSUE THREAD

**Issue by edmondscommerce** [gossi/php-code-generator#53]
Using this library along with other things that use php-parser, we are now at the stage where php-parser has gone to version 4, but this library maxes out at version 3

For this library to continue to be useful, the dependencies need to be kept up to date

**Comment by gossi** [comment]
Definitely! Will touch it the next days/week. I paused php a good amount of time. Thanks for the reminder!

**Comment by edmondscommerce** [comment]
Awesome, looking forwards to it!

**Comment by gossi** [comment]
Done, I released `v0.6-beta.1`, see #54 to make this stable.
