### ISSUE TITLE
More thorough docs?

### ISSUE THREAD

**Issue by mattsah** [gossi/php-code-generator#6]
Are there any more thorough docs?

**Comment by gossi** [comment]
Basically, more docs is always good :wink: What kind of docs you are looking for?

PS: Could you create another issue for the `setBody()` to keep things separated - thanks.

**Comment by mattsah** [comment]
I moved the other part to a separate ticket.

With respect to docs, perhaps I'm wrongly assuming that it does more.  That's part of why I included the method body stuff originally in this issue.  But, I'm guessing it does class properties?  Does it only generate dockblocks from the defined properties?  Any way to add manual chunks?  Things like that.  The README just felt a bit light.

**Comment by gossi** [comment]
Ok, you got me motivated, I wrote those docs: https://php-code-generator.readthedocs.org
Would be glad to get some feedback on this.

**Comment by mattsah** [comment]
I'll be looking into converting my ORMs model generation to it, so I'll have some feedback in another week or so, have a few other pieces to put together first.  I'll let you know then.

**Comment by gossi** [comment]
I updated the docs again. I gonna close this. If you are missing some part or need more exaplantion on a specific topic, please open another issue.
